notion: 代理设置、正则匹配、获取历史签到、二维码签到等功能请查看文档 documents/用户配置高级教程.md
# YAML有引用和锚点，可以节省配置长度(备注:锚点要放在引用的前面)(可以参考https://www.runoob.com/w3cnote/yaml-intro.html)
# ======================================================================
# 全局设置
# ======================================================================
apple: "https://apple.ruoli.cc/captcha/validate" # 请在「https://apple.ruoli.cc/captcha/docs」获取图形验证码识别API
locationOffsetRange: 50 # 签到坐标随机偏移范围(单位：米)(可以为0)
maxTry: 1 # 最大尝试次数
logDir: "_log/" # 日志保存地址
delay: [5, 10] # 多用户时，各用户之间任务执行延迟(时间范围可以使用浮点数)
captcha: # 图片验证码识别(不需要可以不填)
  tencentSecretId: "" # 腾讯云OCR
  tencentSecretKey: "" # 腾讯云OCR
  captchaLen: 4 # 验证码长度
sendMessage: # 推送函数的整体运行情况(不需要的项目不用填，可以删掉或者放着不管)
  pushplus_parameters: "a04f77e6a9c54e16a33179ef14652652" # pushplus(https://www.pushplus.plus)参数，填入令牌(token)即可推送。也可以填入"token=xxx&topic=xxx"形式自定义更多参数
  
# ======================================================================
# 用户组配置(填写自己所需的类型，并删掉不需要的。可以配置多用户(复制粘贴多配置几个就好)。)
# ======================================================================
users: #!!!!!别误删了这一行!!!!!
  
  - # !!!!!!!!!!配置多用户时不要遗漏这一行("- "代表数组里一项的开始)!!!!!!!!!!
    # 查寝模板=======
    # 通用必填项-------
    type: 2 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: 普洱学院 # 学校全称
    username: "1906041138" # 学号或者工号--张思
    password: "zs123456" # 密码
    # 一般需填项-------
    signLevel: 0 # 签到等级[0:正常签到|1:请假后依然签到|2:请假或已经打卡后依然重复签到]
    title: 0 # [str:签到任务的标题|0:取最后一个未签到的任务]
    abnormalReason: "" # abnormalReason 反馈信息
    photo: "sign-photo" # 签到照片(不需要可不填)
    # 经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
    lon: 101.005566 # 经度(特别提醒!!!手机GPS是WGS-84坐标系，普通地图是GCJ02坐标系，今日校园用的是BD09坐标系。不要耍小聪明去其他地方获取坐标)
    lat: 22.773629 # 纬度
    address: "中国云南省普洱市思茅区思茅镇洗马河旅游环线" # 地址信息
    proxy:
      type: panda
      api: http://pandavip.xiongmaodaili.com/xiongmao-web/apiPlus/vgl?secret=b31a0754a574fbc49e108289fcc8e294&orderNo=VGL20230415192520LT4XRDfq&count=200&isTxt=0&proxyType=1&validTime=0&removal=0&cityIds=
      maxRetry: 3
      
  - # !!!!!!!!!!配置多用户时不要遗漏这一行("- "代表数组里一项的开始)!!!!!!!!!!
    # 查寝模板=======
    # 通用必填项-------
    type: 2 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: 普洱学院 # 学校全称
    username: "1906041108" # 学号或者工号--李晗骁
    password: "qq542297441" # 密码
    # 一般需填项-------
    signLevel: 0 # 签到等级[0:正常签到|1:请假后依然签到|2:请假或已经打卡后依然重复签到]
    title: 0 # [str:签到任务的标题|0:取最后一个未签到的任务]
    abnormalReason: "" # abnormalReason 反馈信息
    photo: "sign-photo" # 签到照片(不需要可不填)
    # 经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
    lon: 101.005566 # 经度(特别提醒!!!手机GPS是WGS-84坐标系，普通地图是GCJ02坐标系，今日校园用的是BD09坐标系。不要耍小聪明去其他地方获取坐标)
    lat: 22.773629 # 纬度
    address: "中国云南省普洱市思茅区思茅镇洗马河旅游环线" # 地址信息
    proxy:
      type: panda
      api: http://pandavip.xiongmaodaili.com/xiongmao-web/apiPlus/vgl?secret=b31a0754a574fbc49e108289fcc8e294&orderNo=VGL20230415192520LT4XRDfq&count=200&isTxt=0&proxyType=1&validTime=0&removal=0&cityIds=
      maxRetry: 3
  
  - # !!!!!!!!!!配置多用户时不要遗漏这一行("- "代表数组里一项的开始)!!!!!!!!!!
    # 查寝模板=======
    # 通用必填项-------
    type: 2 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: 普洱学院 # 学校全称
    username: "2206069104" # 学号或者工号--陈恩泽
    password: "cez2000831" # 密码
    # 一般需填项-------
    signLevel: 0 # 签到等级[0:正常签到|1:请假后依然签到|2:请假或已经打卡后依然重复签到]
    title: 0 # [str:签到任务的标题|0:取最后一个未签到的任务]
    abnormalReason: "" # abnormalReason 反馈信息
    photo: "sign-photo" # 签到照片(不需要可不填)
    # 经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
    lon: 101.005566 # 经度(特别提醒!!!手机GPS是WGS-84坐标系，普通地图是GCJ02坐标系，今日校园用的是BD09坐标系。不要耍小聪明去其他地方获取坐标)
    lat: 22.773629 # 纬度
    address: "中国云南省普洱市思茅区思茅镇洗马河旅游环线" # 地址信息
    proxy:
      type: panda
      api: http://pandavip.xiongmaodaili.com/xiongmao-web/apiPlus/vgl?secret=b31a0754a574fbc49e108289fcc8e294&orderNo=VGL20230415192520LT4XRDfq&count=200&isTxt=0&proxyType=1&validTime=0&removal=0&cityIds=
      maxRetry: 3
    
  - # !!!!!!!!!!配置多用户时不要遗漏这一行("- "代表数组里一项的开始)!!!!!!!!!!
    # 查寝模板=======
    # 通用必填项-------
    type: 2 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: 普洱学院 # 学校全称
    username: "2206069233" # 学号或者工号--夏发普
    password: "2206069233XfP?" # 密码
    # 一般需填项-------
    signLevel: 0 # 签到等级[0:正常签到|1:请假后依然签到|2:请假或已经打卡后依然重复签到]
    title: 0 # [str:签到任务的标题|0:取最后一个未签到的任务]
    abnormalReason: "" # abnormalReason 反馈信息
    photo: "sign-photo" # 签到照片(不需要可不填)
    # 经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
    lon: 101.005566 # 经度(特别提醒!!!手机GPS是WGS-84坐标系，普通地图是GCJ02坐标系，今日校园用的是BD09坐标系。不要耍小聪明去其他地方获取坐标)
    lat: 22.773629 # 纬度
    address: "中国云南省普洱市思茅区思茅镇洗马河旅游环线" # 地址信息
    proxy:
      type: panda
      api: http://pandavip.xiongmaodaili.com/xiongmao-web/apiPlus/vgl?secret=b31a0754a574fbc49e108289fcc8e294&orderNo=VGL20230415192520LT4XRDfq&count=200&isTxt=0&proxyType=1&validTime=0&removal=0&cityIds=
      maxRetry: 3
  
  - # !!!!!!!!!!配置多用户时不要遗漏这一行("- "代表数组里一项的开始)!!!!!!!!!!
    # 查寝模板=======
    # 通用必填项-------
    type: 2 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: 普洱学院 # 学校全称
    username: "2206079224" # 学号或者工号--普光鹏
    password: "tgpqq17520" # 密码
    # 一般需填项-------
    signLevel: 0 # 签到等级[0:正常签到|1:请假后依然签到|2:请假或已经打卡后依然重复签到]
    title: 0 # [str:签到任务的标题|0:取最后一个未签到的任务]
    abnormalReason: "" # abnormalReason 反馈信息
    photo: "sign-photo" # 签到照片(不需要可不填)
    # 经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
    lon: 101.005566 # 经度(特别提醒!!!手机GPS是WGS-84坐标系，普通地图是GCJ02坐标系，今日校园用的是BD09坐标系。不要耍小聪明去其他地方获取坐标)
    lat: 22.773629 # 纬度
    address: "中国云南省普洱市思茅区思茅镇洗马河旅游环线" # 地址信息
    proxy:
      type: panda
      api: http://pandavip.xiongmaodaili.com/xiongmao-web/apiPlus/vgl?secret=b31a0754a574fbc49e108289fcc8e294&orderNo=VGL20230415192520LT4XRDfq&count=200&isTxt=0&proxyType=1&validTime=0&removal=0&cityIds=
      maxRetry: 3
      
  - # !!!!!!!!!!配置多用户时不要遗漏这一行("- "代表数组里一项的开始)!!!!!!!!!!
    # 查寝模板=======
    # 通用必填项-------
    type: 2 # 任务类型[信息收集:0|签到:1|查寝:2|教师工作日志:3|政工签到:4]
    schoolName: 普洱学院 # 学校全称
    username: "1906041108" # 学号或者工号--普光鹏
    password: "8991106ZZZWWE" # 密码
    # 一般需填项-------
    signLevel: 0 # 签到等级[0:正常签到|1:请假后依然签到|2:请假或已经打卡后依然重复签到]
    title: 0 # [str:签到任务的标题|0:取最后一个未签到的任务]
    abnormalReason: "" # abnormalReason 反馈信息
    photo: "sign-photo" # 签到照片(不需要可不填)
    # 经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
    lon: 101.005566 # 经度(特别提醒!!!手机GPS是WGS-84坐标系，普通地图是GCJ02坐标系，今日校园用的是BD09坐标系。不要耍小聪明去其他地方获取坐标)
    lat: 22.773629 # 纬度
    address: "中国云南省普洱市思茅区思茅镇洗马河旅游环线" # 地址信息
    proxy:
      type: panda
      api: http://pandavip.xiongmaodaili.com/xiongmao-web/apiPlus/vgl?secret=b31a0754a574fbc49e108289fcc8e294&orderNo=VGL20230415192520LT4XRDfq&count=200&isTxt=0&proxyType=1&validTime=0&removal=0&cityIds=
      maxRetry: 3
  
